---
- name: Remove resolvconf on Debian systems
  package:
    name: resolvconf
    state: absent
  when: ansible_os_family == 'Debian'

- name: Install /etc/resolv.conf
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
